-- Importação de alunos 2026/2027 — gerado automaticamente a partir de
-- 'Dadosalunos5ateliceu(Alunos Ativos 20262027).csv' (555 alunos, 30 turmas).
-- Idempotente: pode ser corrido mais que uma vez sem duplicar ciclos/turmas/alunos já importados por este script.
BEGIN;

-- 1) Ciclos (4, mapeados 1:1 a partir da coluna 'Aluno: Curso' do CSV)
INSERT INTO ciclos (nome)
SELECT v.nome FROM (VALUES
  ('3º Ciclo'),
  ('2º Ciclo'),
  ('R25 - Curso de Técnico de Informática Sistemas'),
  ('Ciências e Tecnologias')
) AS v(nome)
WHERE NOT EXISTS (SELECT 1 FROM ciclos c WHERE c.nome = v.nome);

-- 2) Turmas (30 no total)
INSERT INTO turmas (nome, ano, ciclo_id)
SELECT v.nome, v.ano, c.id
FROM (VALUES
  ('A', 5, '2º Ciclo'),
  ('B', 5, '2º Ciclo'),
  ('C', 5, '2º Ciclo'),
  ('A', 6, '2º Ciclo'),
  ('B', 6, '2º Ciclo'),
  ('C', 6, '2º Ciclo'),
  ('A', 7, '3º Ciclo'),
  ('B', 7, '3º Ciclo'),
  ('C', 7, '3º Ciclo'),
  ('A', 8, '3º Ciclo'),
  ('B', 8, '3º Ciclo'),
  ('C', 8, '3º Ciclo'),
  ('A', 9, '3º Ciclo'),
  ('B', 9, '3º Ciclo'),
  ('A', 10, 'Ciências e Tecnologias'),
  ('B', 10, 'Ciências e Tecnologias'),
  ('C', 10, 'Ciências e Tecnologias'),
  ('A', 11, 'Ciências e Tecnologias'),
  ('B', 11, 'Ciências e Tecnologias'),
  ('C', 11, 'Ciências e Tecnologias'),
  ('A', 12, 'Ciências e Tecnologias'),
  ('B', 12, 'Ciências e Tecnologias'),
  ('A1', 10, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('B1', 10, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('C1', 10, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('A1', 11, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('B1', 11, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('C1', 11, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('A1', 12, 'R25 - Curso de Técnico de Informática Sistemas'),
  ('B1', 12, 'R25 - Curso de Técnico de Informática Sistemas')
) AS v(nome, ano, ciclo_nome)
JOIN ciclos c ON c.nome = v.ciclo_nome
WHERE NOT EXISTS (
  SELECT 1 FROM turmas t WHERE t.nome = v.nome AND t.ano = v.ano AND t.ciclo_id = c.id
);

-- 3) Alunos (555 no total)
INSERT INTO alunos (nome, ano, turma, turma_id, ciclo_id)
SELECT v.nome, v.ano, v.turma, t.id, t.ciclo_id
FROM (VALUES
  ('Afonso Maria Alves Batista', 9, 'B', '3º Ciclo'),
  ('Alexandre Maria Henriques de Lancastre da Cruz Almeida', 9, 'A', '3º Ciclo'),
  ('António Maria de Matias Fernandes Gonçalves Correia', 9, 'B', '3º Ciclo'),
  ('Bartolomeu dos Mártires Rebelo de Andrade Saraiva de Ponte', 9, 'B', '3º Ciclo'),
  ('Benedita Silva Pinto Vaz Pinto', 9, 'A', '3º Ciclo'),
  ('Bryan Filipe Rodrigues de Oliveira e Costa', 9, 'B', '3º Ciclo'),
  ('Carminho de Luz Gerdes Trigoso Jordão Rodhner', 9, 'A', '3º Ciclo'),
  ('Carolina Macias Ribeiro dos Santos', 9, 'A', '3º Ciclo'),
  ('Carolina Simões Andrade', 9, 'A', '3º Ciclo'),
  ('Constança Carôco Pedro Maciel Cardoso', 9, 'B', '3º Ciclo'),
  ('Diana Gonçalves Perfeito', 9, 'A', '3º Ciclo'),
  ('Domingos Maria Calejo Pires Navarro de Castro', 9, 'B', '3º Ciclo'),
  ('Duarte Moreno Ramos Rodrigues', 9, 'B', '3º Ciclo'),
  ('Filipe de Paula da Fonseca Ferreira Tavares de Sena', 9, 'A', '3º Ciclo'),
  ('Francisca Leite Teixeira dos Santos Ferreira', 9, 'A', '3º Ciclo'),
  ('Francisco de Ladeira Afonso', 9, 'A', '3º Ciclo'),
  ('Francisco Felix Miranda Carvalho', 9, 'A', '3º Ciclo'),
  ('Francisco Miguel Varela Borges', 9, 'A', '3º Ciclo'),
  ('Guanquan Wang', 9, 'A', '3º Ciclo'),
  ('Guanzhe Wang', 9, 'A', '3º Ciclo'),
  ('Inês Mantero Bilbao Jardim Gonçalves', 9, 'A', '3º Ciclo'),
  ('José Maria Vasques Marinho Crespo Marques', 9, 'A', '3º Ciclo'),
  ('Lara Menezes da Vinha', 9, 'B', '3º Ciclo'),
  ('Leonor da Costa Gomes', 9, 'B', '3º Ciclo'),
  ('Leonor Jorge Amaro', 9, 'A', '3º Ciclo'),
  ('Lourenço Cartaxo Cid Ponte', 9, 'B', '3º Ciclo'),
  ('Lourenço Maria Cabral de Castro Gouveia', 9, 'B', '3º Ciclo'),
  ('Lourenço Maria Vigon Biard Antunes', 9, 'A', '3º Ciclo'),
  ('Luciana Cumbue Pelo Tchenhe', 9, 'A', '3º Ciclo'),
  ('Luís de Albuquerque Moreira Rato de Castro', 9, 'A', '3º Ciclo'),
  ('Luísa de Santa Maria Bilbao Osório de Castro', 9, 'B', '3º Ciclo'),
  ('Madalena Gonçalves Gomes', 9, 'B', '3º Ciclo'),
  ('Manuel Maria de Almeida Ruivo Leal', 9, 'B', '3º Ciclo'),
  ('Marcos Tavares de Sousa', 9, 'A', '3º Ciclo'),
  ('Margarida Wu Zhou', 9, 'B', '3º Ciclo'),
  ('Maria Carlota Simões de Almeida Plantier', 9, 'A', '3º Ciclo'),
  ('Maria da Pureza Simões de Almeida Plantier', 9, 'A', '3º Ciclo'),
  ('Maria do Carmo Azevedo Ferraz Galvão de Melo', 9, 'B', '3º Ciclo'),
  ('Maria Francisca Monteiro Mesquita e Coelho', 9, 'B', '3º Ciclo'),
  ('Maria Francisca Sebastião Lucas', 9, 'B', '3º Ciclo'),
  ('Maria Mateus Pereira e Serra', 9, 'B', '3º Ciclo'),
  ('Maria Matias de Sousa Moura', 9, 'A', '3º Ciclo'),
  ('Maria Paula Avilez da Silva', 9, 'B', '3º Ciclo'),
  ('Maria Pia Pedroso Próspero dos Santos', 9, 'B', '3º Ciclo'),
  ('Maria Teresa Simões de Almeida Plantier', 9, 'A', '3º Ciclo'),
  ('Martim Fonseca de Jesus Sequeira', 9, 'A', '3º Ciclo'),
  ('Mateus José de Mello Garcia', 9, 'B', '3º Ciclo'),
  ('Mateus Santos Novo', 9, 'A', '3º Ciclo'),
  ('Mathilda Sophia Sloet Tot Everlo Simões de Almeida', 9, 'B', '3º Ciclo'),
  ('Mercedes O Connor Shirley Baião', 9, 'A', '3º Ciclo'),
  ('Mia Leonor da Silva Correia', 9, 'A', '3º Ciclo'),
  ('Pedro do Carmo Pereira de Melo Parente João', 9, 'B', '3º Ciclo'),
  ('Rafael Ramiro Rocha Morais', 9, 'B', '3º Ciclo'),
  ('Rodrigo Lorena Soller Coelho Nunes', 9, 'B', '3º Ciclo'),
  ('Rodrigo Marques Candeias', 9, 'A', '3º Ciclo'),
  ('Salvador Maria Anjos Correia de Sá', 9, 'B', '3º Ciclo'),
  ('Santiago André Barbeiro', 9, 'A', '3º Ciclo'),
  ('Santiago Monteiro Sapina Moita Santos', 9, 'A', '3º Ciclo'),
  ('Sofia Gonçalves Gaspar', 9, 'B', '3º Ciclo'),
  ('Tiago Daniel Pereira Rodrigues Coelho', 9, 'B', '3º Ciclo'),
  ('Vasco Tibério Fernandes dos Santos Catarino', 9, 'A', '3º Ciclo'),
  ('Victor Huang', 9, 'A', '3º Ciclo'),
  ('Yufei Xin', 9, 'B', '3º Ciclo'),
  ('Yumiao Yang', 9, 'B', '3º Ciclo'),
  ('Abra Josee Chung Yan Wong', 8, 'B', '3º Ciclo'),
  ('Afonso Anahory Rebelo de Barros', 8, 'B', '3º Ciclo'),
  ('Afonso Matias de Sousa Moura', 8, 'C', '3º Ciclo'),
  ('Ana Ennes Magalhães e Meneses Ferros', 8, 'B', '3º Ciclo'),
  ('Angelina Soares Carvalho', 8, 'C', '3º Ciclo'),
  ('António Francisco Pisani Burnay Tojal', 8, 'C', '3º Ciclo'),
  ('Beatriz Montero da Silva', 8, 'B', '3º Ciclo'),
  ('Benedita Rafael Galvão e Salgado', 8, 'C', '3º Ciclo'),
  ('Camila Priolli Berti', 8, 'A', '3º Ciclo'),
  ('Carminho de Siena Sousa Neves', 8, 'A', '3º Ciclo'),
  ('Constança da Câmara Pereira Pinheiro de Melo', 8, 'C', '3º Ciclo'),
  ('Daniel Sapina Silvestre', 8, 'A', '3º Ciclo'),
  ('Diana Palma Alentejano Hassan', 8, 'C', '3º Ciclo'),
  ('Dinis Galvão Veiga Rebelo', 8, 'C', '3º Ciclo'),
  ('Dinis Guilherme Veiga Marques Nunes', 8, 'A', '3º Ciclo'),
  ('Dmitrii Diupyn', 8, 'A', '3º Ciclo'),
  ('Edmilson da Conceição Marques Mesquita Ferreira', 8, 'A', '3º Ciclo'),
  ('Eduardo Maria Pereira da Costa Sequeira Nunes', 8, 'C', '3º Ciclo'),
  ('Estêvão Maria de Castro Carneiro Líbano Monteiro', 8, 'C', '3º Ciclo'),
  ('Filipe Alexandre dos Santos Correia', 8, 'A', '3º Ciclo'),
  ('Francisca Duarte Palma', 8, 'C', '3º Ciclo'),
  ('Francisca Martins César', 8, 'B', '3º Ciclo'),
  ('Francisco Lousada de Jesus', 8, 'C', '3º Ciclo'),
  ('Francisco Quinteiro Louro de Carvalho Abrantes', 8, 'A', '3º Ciclo'),
  ('Frederico Dias de Freitas Camilo Alves', 8, 'B', '3º Ciclo'),
  ('Gonçalo Jorge Mateus', 8, 'C', '3º Ciclo'),
  ('Guilherme Dionisio Mota Nunes', 8, 'A', '3º Ciclo'),
  ('João Maria Teotónio Pereira Bourbon Ribeiro', 8, 'C', '3º Ciclo'),
  ('José Gago da Cunha', 8, 'B', '3º Ciclo'),
  ('Júlia Duarte Valente Estiveira', 8, 'C', '3º Ciclo'),
  ('Kai Rui Lou', 8, 'B', '3º Ciclo'),
  ('Laura Baeta Mendonça', 8, 'C', '3º Ciclo'),
  ('Leonor Ribeiro Cardoso dos Anjos Marques', 8, 'A', '3º Ciclo'),
  ('Letícia Alexandre Samuel', 8, 'B', '3º Ciclo'),
  ('Loic Ye', 8, 'C', '3º Ciclo'),
  ('Lourenço O Connor Shirley Baião', 8, 'B', '3º Ciclo'),
  ('Lourenço Ventura Rodrigues Coelho Pacheco', 8, 'B', '3º Ciclo'),
  ('Madalena Arneiro Fernandes dos Santos Tomázio', 8, 'A', '3º Ciclo'),
  ('Madalena Marques Stilwell', 8, 'A', '3º Ciclo'),
  ('Manuel Francisco Araújo Frois Ferreira', 8, 'B', '3º Ciclo'),
  ('Manuel Vassalo Ribeiro Safont Tavares', 8, 'B', '3º Ciclo'),
  ('Maria Ana de Mendia de Castro de Lima Mayer', 8, 'A', '3º Ciclo'),
  ('Maria Constança de Carvalho Antunes', 8, 'C', '3º Ciclo'),
  ('Maria da Assunção Rebelo de Andrade Saraiva de Ponte', 8, 'B', '3º Ciclo'),
  ('Maria do Carmo de Castro da Cunha Beltrão', 8, 'B', '3º Ciclo'),
  ('Maria do Carmo Santos Gonçalves', 8, 'A', '3º Ciclo'),
  ('Maria Francisca Pisani Burnay Tojal', 8, 'B', '3º Ciclo'),
  ('Maria Gabriela Faceira Faria', 8, 'A', '3º Ciclo'),
  ('Maria Inês Landeiro Capelo da Mota Caldeira', 8, 'C', '3º Ciclo'),
  ('Maria Inês Parreira Martins', 8, 'B', '3º Ciclo'),
  ('Maria Leonor Veiga Marques Nunes', 8, 'C', '3º Ciclo'),
  ('Maria Rita Roque Alberto', 8, 'B', '3º Ciclo'),
  ('Maria Teresa Caetano Martin Lamy da Fontoura', 8, 'A', '3º Ciclo'),
  ('Mário Claudiu Muresan', 8, 'A', '3º Ciclo'),
  ('Marta de Moser Arantes Rocha Pereira', 8, 'C', '3º Ciclo'),
  ('Marta de Souza de Brito de Mendonça Mergulhão', 8, 'A', '3º Ciclo'),
  ('Martim Maria Quartin Simões de Almeida', 8, 'A', '3º Ciclo'),
  ('Matilde Cardoso Gonçalves', 8, 'A', '3º Ciclo'),
  ('Miriam Andreia Tanasa', 8, 'B', '3º Ciclo'),
  ('Paloma de Jesus Gerdes Trigoso Jordão Rodhner', 8, 'A', '3º Ciclo'),
  ('Pedro Manuel Pardal de Vila Selas', 8, 'A', '3º Ciclo'),
  ('Ruben Cai', 8, 'C', '3º Ciclo'),
  ('Salvador Mesquita Guerra Centeno Mendonça', 8, 'A', '3º Ciclo'),
  ('Sara Simões Rosado Machado de Almeida', 8, 'C', '3º Ciclo'),
  ('Teresa Azevedo Ferraz Galvão de Melo', 8, 'C', '3º Ciclo'),
  ('Teresa Pedro Milagre', 8, 'C', '3º Ciclo'),
  ('Teresinha Sampaio Marques e Morais Barbosa', 8, 'B', '3º Ciclo'),
  ('Vivian Sophia Zickermann Pires', 8, 'A', '3º Ciclo'),
  ('Vladislav Ovchynnikov', 8, 'A', '3º Ciclo'),
  ('Alejandro Burguete Botelho Cardoso Málaga', 7, 'A', '3º Ciclo'),
  ('André de Paula da Fonseca Ferreira Tavares de Sena', 7, 'A', '3º Ciclo'),
  ('Ângela Zhou', 7, 'B', '3º Ciclo'),
  ('António Maria Noronha de Mello Bonneville', 7, 'B', '3º Ciclo'),
  ('Benedita Moita Ramos Cosme Tomaz', 7, 'A', '3º Ciclo'),
  ('Bernardo Maria Afonso de Castro Rodrigues', 7, 'B', '3º Ciclo'),
  ('Caetana Gonzalez Rey de Sá Lima', 7, 'C', '3º Ciclo'),
  ('Caetana Torres Helena da Cruz Reis', 7, 'C', '3º Ciclo'),
  ('Carolina da Silva Marcos', 7, 'A', '3º Ciclo'),
  ('Carolina Reduto de Moura Gil', 7, 'C', '3º Ciclo'),
  ('Catarina Maria Duarte Clemente', 7, 'B', '3º Ciclo'),
  ('Clara Saldanha Mena e Silva', 7, 'A', '3º Ciclo'),
  ('Constança Maria Henriques Félix Olas', 7, 'B', '3º Ciclo'),
  ('Daniel Rainer Jenkinson', 7, 'A', '3º Ciclo'),
  ('David Adrian Craciun Copeto Gomes', 7, 'C', '3º Ciclo'),
  ('Duarte Carvalho e Silva', 7, 'B', '3º Ciclo'),
  ('Duarte Maria de Quintanilha e Mendonça Lopes Cardoso', 7, 'C', '3º Ciclo'),
  ('Evelyn Grace Ward', 7, 'B', '3º Ciclo'),
  ('Francisco Manuel Pedrosa Silvestre', 7, 'C', '3º Ciclo'),
  ('Henrique Alexandre Figueira da Fonseca e Ferreira Conceição', 7, 'C', '3º Ciclo'),
  ('Henrique José de Lancastre Guedes da Cruz Almeida', 7, 'C', '3º Ciclo'),
  ('Iara Vera Cruz de Sousa', 7, 'C', '3º Ciclo'),
  ('Isabel Mineiro Fortuna Batista Nunes', 7, 'C', '3º Ciclo'),
  ('Isis Maria Pardal Tempera', 7, 'C', '3º Ciclo'),
  ('Joana Filipa da Conceição Mateus Alves', 7, 'A', '3º Ciclo'),
  ('João Maria da Silva Dias Januário Fragoso', 7, 'B', '3º Ciclo'),
  ('João Maria do Monte Rosa Pacheco Rodrigues', 7, 'B', '3º Ciclo'),
  ('João Maria Máximo Martelo Caldeira Morais', 7, 'C', '3º Ciclo'),
  ('Júlio Chenxi Zhu', 7, 'B', '3º Ciclo'),
  ('Laura Pinto da Cruz', 7, 'C', '3º Ciclo'),
  ('Leonor Isabel Castro Ferreirinho', 7, 'C', '3º Ciclo'),
  ('Leonor Martins Amorim', 7, 'B', '3º Ciclo'),
  ('Leonor Sofia Santos Silva Nogueira', 7, 'C', '3º Ciclo'),
  ('Lourenço Martins Pereira', 7, 'A', '3º Ciclo'),
  ('Lourenço Pallister e Calaim', 7, 'B', '3º Ciclo'),
  ('Madalena Torre do Valle Monjardino', 7, 'A', '3º Ciclo'),
  ('Manuel Maria Saraiva Gonçalves dos Santos Frazão', 7, 'B', '3º Ciclo'),
  ('Maria Clara Coelho dos Santos Tavares', 7, 'B', '3º Ciclo'),
  ('Maria Clara da Silva Mendes', 7, 'C', '3º Ciclo'),
  ('Maria Constança Penas Vieira dos Santos', 7, 'A', '3º Ciclo'),
  ('Maria do Carmo Rebelo de Andrade Saraiva de Ponte', 7, 'A', '3º Ciclo'),
  ('Maria do Pilar de Carvalho Antunes', 7, 'A', '3º Ciclo'),
  ('Maria Goldschmidt Conde Pinto Coelho', 7, 'A', '3º Ciclo'),
  ('Maria Helena Rebelo de Andrade da Cunha Ferreira', 7, 'A', '3º Ciclo'),
  ('Maria Leonor Correia de Campos Edwards', 7, 'B', '3º Ciclo'),
  ('Maria Teresa Coelho e Campos da Cruz Almeida', 7, 'B', '3º Ciclo'),
  ('Maria Teresa Leitão Courinha', 7, 'C', '3º Ciclo'),
  ('Matilde Alves dos Santos Mexia', 7, 'B', '3º Ciclo'),
  ('Miguel Kristian Helovuori e Santos', 7, 'C', '3º Ciclo'),
  ('Oliver Sean Youngman', 7, 'C', '3º Ciclo'),
  ('Paula Rodriguez de Freitas', 7, 'B', '3º Ciclo'),
  ('Pedro Maria Pereira da Costa Sequeira Nunes', 7, 'A', '3º Ciclo'),
  ('Raquel Vitorino Gonçalves de Moura', 7, 'A', '3º Ciclo'),
  ('Rodrigo Cruz Rodrigues Teixeira', 7, 'B', '3º Ciclo'),
  ('Rodrigo Mantero Bilbao Jardim Gonçalves', 7, 'A', '3º Ciclo'),
  ('Rodrigo Miguel Teixeira de Almeida Gonçalves Figueiredo', 7, 'C', '3º Ciclo'),
  ('Rosália Nene Marcia Pelo Tchenhe', 7, 'B', '3º Ciclo'),
  ('Sara de Melo Guimarães Barbosa', 7, 'A', '3º Ciclo'),
  ('Tiago Diniz Ramiro Pires', 7, 'B', '3º Ciclo'),
  ('Tiago Elói Rito da Costa', 7, 'A', '3º Ciclo'),
  ('Tomás Horácio Felício Nunes Tomás da Cruz', 7, 'C', '3º Ciclo'),
  ('Tomás Pereira de Figueiredo', 7, 'B', '3º Ciclo'),
  ('Vasco Gonçalves Perfeito', 7, 'C', '3º Ciclo'),
  ('Vasco Mateus Lúcio', 7, 'A', '3º Ciclo'),
  ('Vicente Araújo Fontes Castanheira André', 7, 'A', '3º Ciclo'),
  ('Vicente Filipe Pombo Duarte', 7, 'C', '3º Ciclo'),
  ('Vitória André Barbeiro', 7, 'C', '3º Ciclo'),
  ('Afonso Barbosa Machado', 6, 'C', '2º Ciclo'),
  ('Afonso Rodrigues de Sousa', 6, 'A', '2º Ciclo'),
  ('Alice Simões Rosado Machado de Almeida', 6, 'A', '2º Ciclo'),
  ('André Maria Gentil Quina Dias de Carvalho', 6, 'A', '2º Ciclo'),
  ('António Maria Pereira Coutinho de Morais', 6, 'A', '2º Ciclo'),
  ('Benedita Baeta Fernandes', 6, 'B', '2º Ciclo'),
  ('Benedita Maria Steglich Canas Borges Luís', 6, 'B', '2º Ciclo'),
  ('Bernardo de Sousa Uva Vicente Simões', 6, 'B', '2º Ciclo'),
  ('Caetano José Henriques de Lancastre da Cruz Almeida', 6, 'A', '2º Ciclo'),
  ('Carlota Duarte Sequeira', 6, 'B', '2º Ciclo'),
  ('Carlota Maria Cardoso Pinto Pereira Forjaz', 6, 'B', '2º Ciclo'),
  ('Carlota Sousa Araújo Tavares Delgado', 6, 'C', '2º Ciclo'),
  ('Clara Ferreira dos Reis Tomé de Jesus', 6, 'A', '2º Ciclo'),
  ('Clara Gonçalves Pedro da Fonseca', 6, 'C', '2º Ciclo'),
  ('Delia Florina Stepanescu Vraja', 6, 'B', '2º Ciclo'),
  ('Diogo Vistas Ventura', 6, 'C', '2º Ciclo'),
  ('Domingos Pereira de Gouveia Correia de Campos', 6, 'A', '2º Ciclo'),
  ('Duarte Alexandre Quintas Banora', 6, 'C', '2º Ciclo'),
  ('Francisca Marques dos Santos Hasse de Oliveira', 6, 'B', '2º Ciclo'),
  ('Francisco Luís Guerreiro Cruz Miranda de Melo', 6, 'B', '2º Ciclo'),
  ('Francisco Roque Alberto', 6, 'B', '2º Ciclo'),
  ('Frederica Sampaio Marques e Morais Barbosa', 6, 'C', '2º Ciclo'),
  ('Frederico José Fletcher Moreira Rato de Castro', 6, 'C', '2º Ciclo'),
  ('Frederico Maria Lança Cordeiro José de Mello', 6, 'A', '2º Ciclo'),
  ('Gabriel Menezes da Vinha', 6, 'B', '2º Ciclo'),
  ('Gonçalo Teixeira da Costa', 6, 'C', '2º Ciclo'),
  ('Henrique Chen Zheng', 6, 'B', '2º Ciclo'),
  ('Inês de Medeiros Carreiro Maldonado Ascensão', 6, 'C', '2º Ciclo'),
  ('Isabel Saldaña Pinheiro', 6, 'C', '2º Ciclo'),
  ('Isabel Vasques Marinho Crespo Marques', 6, 'C', '2º Ciclo'),
  ('Joana Arneiro Fernandes dos Santos Tomázio', 6, 'B', '2º Ciclo'),
  ('João Carvalhais de Oliveira', 6, 'A', '2º Ciclo'),
  ('José Ferreira Leitão', 6, 'C', '2º Ciclo'),
  ('José Maria Bastos Pacheco Mateus Garcia', 6, 'A', '2º Ciclo'),
  ('José Maria Calado Tomaz', 6, 'C', '2º Ciclo'),
  ('Leonor Fonseca Verde de Sousa', 6, 'C', '2º Ciclo'),
  ('Leonor Teixeira da Costa', 6, 'A', '2º Ciclo'),
  ('Leonor Wolf Stock', 6, 'A', '2º Ciclo'),
  ('Lourenço Queiroz Soares Furtado', 6, 'B', '2º Ciclo'),
  ('Lucas Giovani Lourenço Duarte Leitão', 6, 'A', '2º Ciclo'),
  ('Luís Fernandes Ronda', 6, 'B', '2º Ciclo'),
  ('Luz Vassalo Ribeiro Safont Tavares', 6, 'C', '2º Ciclo'),
  ('Madalena Fonseca Verde de Sousa', 6, 'B', '2º Ciclo'),
  ('Manuel Pedro Milagre', 6, 'C', '2º Ciclo'),
  ('Manuel Vieira de Freitas Simões', 6, 'B', '2º Ciclo'),
  ('Margarida da Silva Lourenço Lopes', 6, 'B', '2º Ciclo'),
  ('Maria Amélia Gouveia Carreiras do Souto Cardoso', 6, 'A', '2º Ciclo'),
  ('Maria da Luz Barreira Miranda de Lencastre Fiuza', 6, 'C', '2º Ciclo'),
  ('Maria do Carmo Bonnet Marques Nunes da Silva', 6, 'A', '2º Ciclo'),
  ('Maria Francisca Albuquerque Ferreira de Freitas Simões', 6, 'C', '2º Ciclo'),
  ('Maria Laura Miranda Antunes', 6, 'A', '2º Ciclo'),
  ('Maria Leonor Kun Ferreira da Silva Príncipe', 6, 'B', '2º Ciclo'),
  ('Maria Luisa Pinheiro e Aragão', 6, 'C', '2º Ciclo'),
  ('Maria Teresa Carreira da Gama Lobo Xavier', 6, 'C', '2º Ciclo'),
  ('Maria Teresa de Vasconcelos e Vaz de São Payo', 6, 'A', '2º Ciclo'),
  ('Mariana dos Santos Covelo Silva Antunes', 6, 'C', '2º Ciclo'),
  ('Mariana Nobre Redol', 6, 'B', '2º Ciclo'),
  ('Mark Claro da Fonseca Scott', 6, 'C', '2º Ciclo'),
  ('Marta Branco Levezinho', 6, 'C', '2º Ciclo'),
  ('Martim Galvão Veiga Rebelo', 6, 'A', '2º Ciclo'),
  ('Martim Maria Godinho Barata Mousinho Lopes', 6, 'C', '2º Ciclo'),
  ('Mateus dos Santos Inácio Gil', 6, 'A', '2º Ciclo'),
  ('Mateus Maria Urmal Santos Garcia', 6, 'C', '2º Ciclo'),
  ('Mónica Anahory Rebelo de Barros', 6, 'A', '2º Ciclo'),
  ('Nuno Maria Pina Antunes Tico', 6, 'B', '2º Ciclo'),
  ('Pedro Hugo de Arruda Schowartz', 6, 'A', '2º Ciclo'),
  ('Pierre-Louis Ambroise Cyriaque Schwerer', 6, 'C', '2º Ciclo'),
  ('Rafael Faustino Lourenço', 6, 'B', '2º Ciclo'),
  ('Salvador Vicente Silva Peralta Duarte', 6, 'A', '2º Ciclo'),
  ('Sara Pereira de Figueiredo', 6, 'A', '2º Ciclo'),
  ('Sitong Lu', 6, 'B', '2º Ciclo'),
  ('Sofia Timóteo Ramos', 6, 'B', '2º Ciclo'),
  ('Vasco Baeta Mendonça', 6, 'B', '2º Ciclo'),
  ('Vasco das Neves Cortês Ribeiro da Silva', 6, 'C', '2º Ciclo'),
  ('Vasco Martha Couto Quintella Supico', 6, 'A', '2º Ciclo'),
  ('Vera de Souza de Brito de Mendonça Mergulhão', 6, 'B', '2º Ciclo'),
  ('Victoria Cardoso da Silva Carvalho', 6, 'B', '2º Ciclo'),
  ('Amadeu Vicente Fernandes Granja', 5, 'C', '2º Ciclo'),
  ('António Lorenzo Pereira Rossini', 5, 'A', '2º Ciclo'),
  ('António Maria Luz Coruche D Orey Assunção', 5, 'A', '2º Ciclo'),
  ('Anya Anggraeni Schmitter', 5, 'A', '2º Ciclo'),
  ('Ariana Bondar Abreu', 5, 'B', '2º Ciclo'),
  ('Aura Justino Gomes', 5, 'A', '2º Ciclo'),
  ('Caetano Marreiros Pimentel', 5, 'C', '2º Ciclo'),
  ('Camila de Alpoim Moreira Madeira Marques', 5, 'C', '2º Ciclo'),
  ('Carolina Ferreira da Silva', 5, 'C', '2º Ciclo'),
  ('Carolina Madureira Pimentel', 5, 'C', '2º Ciclo'),
  ('Clara Ferreira Leitão', 5, 'A', '2º Ciclo'),
  ('Constança da Costa Nogueira', 5, 'B', '2º Ciclo'),
  ('Constança dos Santos Lobo', 5, 'C', '2º Ciclo'),
  ('David Villar Fernandes', 5, 'A', '2º Ciclo'),
  ('Dinis Frazão de Castro Margalho', 5, 'C', '2º Ciclo'),
  ('Dinis Maggioni da Silva Seiceira Mendonça', 5, 'B', '2º Ciclo'),
  ('Duarte Schedel José de Melo', 5, 'C', '2º Ciclo'),
  ('Francesca Frolikov Leitão', 5, 'A', '2º Ciclo'),
  ('Francisca Ribeiro Gomes', 5, 'B', '2º Ciclo'),
  ('Francisco de Assis Gouveia Carreiras do Souto Cardoso', 5, 'B', '2º Ciclo'),
  ('Francisco Duarte Simões Pedro Lourenço', 5, 'A', '2º Ciclo'),
  ('Francisco Xavier Correia Machado de Sousa Soares', 5, 'A', '2º Ciclo'),
  ('Gabriela Burguete Botelho Cardoso Malaga', 5, 'A', '2º Ciclo'),
  ('Gonçalo Fonseca Bancaleiro', 5, 'C', '2º Ciclo'),
  ('Helena Saldanha Mena e Silva', 5, 'A', '2º Ciclo'),
  ('Henrique Maria de Quintanilha e Mendonça Lopes Cardoso', 5, 'A', '2º Ciclo'),
  ('Henrique Van Uden Correia de Sá', 5, 'B', '2º Ciclo'),
  ('Inês Dias Antunes', 5, 'A', '2º Ciclo'),
  ('Inês Lousada de Jesus', 5, 'B', '2º Ciclo'),
  ('Inês Mesquita Guerra Centeno Mendonça', 5, 'B', '2º Ciclo'),
  ('Joana Frazão de Castro Margalho', 5, 'B', '2º Ciclo'),
  ('João Reis Rodrigues', 5, 'C', '2º Ciclo'),
  ('Joaquim Maria Máximo Martelo Caldeira Morais', 5, 'A', '2º Ciclo'),
  ('José Maria Pedroso Próspero dos Santos', 5, 'A', '2º Ciclo'),
  ('José Maria Rebelo de Andrade Saraiva de Ponte', 5, 'B', '2º Ciclo'),
  ('José Tomás Lança Cordeiro José de Mello', 5, 'B', '2º Ciclo'),
  ('Kyara Isabel Semedo Gonzaga', 5, 'B', '2º Ciclo'),
  ('Laura Marta dos Anjos Martins Rosa Lopes', 5, 'A', '2º Ciclo'),
  ('Lourenço Maria Anjos Correia de Sá', 5, 'A', '2º Ciclo'),
  ('Lourenço Maria Múrias Lage Malheiro Duarte', 5, 'C', '2º Ciclo'),
  ('Luz Maria Coelho Dias Lepierre Tinoco', 5, 'C', '2º Ciclo'),
  ('Luzia Maria Rodrigues de Almeida', 5, 'C', '2º Ciclo'),
  ('Lydia Charlotte Ward', 5, 'C', '2º Ciclo'),
  ('Madalena da Silveira Pimentel dos Santos', 5, 'B', '2º Ciclo'),
  ('Margarida Cravo Segão', 5, 'B', '2º Ciclo'),
  ('Maria Carolina Xavier Ferreira Dias Coelho', 5, 'C', '2º Ciclo'),
  ('Maria do Rosário Alves dos Santos Mexia', 5, 'B', '2º Ciclo'),
  ('Maria do Rosário Marques Guedes Moitinho de Almeida', 5, 'A', '2º Ciclo'),
  ('Maria Duarte da Palma Monteiro Velez', 5, 'C', '2º Ciclo'),
  ('Maria Leonor Fonseca Nunes', 5, 'C', '2º Ciclo'),
  ('Maria Luísa Gonçalves de Almeida Leal', 5, 'B', '2º Ciclo'),
  ('Maria Madalena da Silva Dias Januário Fragoso', 5, 'C', '2º Ciclo'),
  ('Maria Margarida Rodrigues Ventura Bravo', 5, 'C', '2º Ciclo'),
  ('Martim Alves Barata da Silva Bastos', 5, 'C', '2º Ciclo'),
  ('Martim Baciu Alberto', 5, 'C', '2º Ciclo'),
  ('Martim Miguel Gordo Tomás', 5, 'A', '2º Ciclo'),
  ('Mia Chechile Figueiredo', 5, 'A', '2º Ciclo'),
  ('Miguel da Costa Cavaco', 5, 'C', '2º Ciclo'),
  ('Miguel Maria de Carvalho Antunes', 5, 'B', '2º Ciclo'),
  ('Mónica Matos Chaves Formosinho Sanchez', 5, 'A', '2º Ciclo'),
  ('Nazaré Pardal Lageiro Tico', 5, 'C', '2º Ciclo'),
  ('Salvador Duarte Valente Estiveira', 5, 'B', '2º Ciclo'),
  ('Santiago SantAna da Silva e Cunha', 5, 'B', '2º Ciclo'),
  ('Sarah Victoria Alves Morais', 5, 'B', '2º Ciclo'),
  ('Sebastian Claro da Fonseca Scott', 5, 'B', '2º Ciclo'),
  ('Tomás Freire de Andrade Ribeirinho dos Santos', 5, 'A', '2º Ciclo'),
  ('Tomás Marques Stilwell', 5, 'C', '2º Ciclo'),
  ('Tomás Martins Carrêto Lereno Monteiro', 5, 'B', '2º Ciclo'),
  ('Vicente Maria de Castro Carneiro Líbano Monteiro', 5, 'A', '2º Ciclo'),
  ('Vicente Maria Sousa Rêgo Teixeira Botelho', 5, 'C', '2º Ciclo'),
  ('Wolf Matheus Flohil de Sousa', 5, 'B', '2º Ciclo'),
  ('Xin Yi Lou', 5, 'A', '2º Ciclo'),
  ('António Maria Rosmaninho Percheiro Castelo dos Santos', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Carlos Jorge Cabral Bandeira Duarte', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Diogo Saldanha Mena E Silva', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Francisco Maria Brás Monteiro Lopes de Carvalho', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('José Maria de Sousa Carvalho Marques Mendes', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('José Maria Duarte Clemente', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Lucas Chen', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Manar Amir Seed Koko Hamad', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria do Rosário Bandeira Paes de Vasconcelos', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria Leonor Sebastião Lucas', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria Madalena Correia de Campos Edwards', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria Teresa Máximo Martelo Caldeira Morais', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Martim de Jesus Ribeiro', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Martim Lourenço Ferreira', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Miguel Alexandro Neves Costea', 12, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Tiago Manuel Pardal de Vila Selas', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Vasco Vasques Marinho Crespo Marques', 12, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Afonso Agostinho Marques Pereira', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Diogo Miguel Falé e Costa Nunes Gonçalves', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Duarte Jorge Teixeira Patrício', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Henrique Araújo de Moura da Silva Barracho', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Júlia Raquel Lobo Ferreira de Magalhães', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Luna Vinhas Barreira', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Madalena Filipe Antunes Roque', 11, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria do Carmo Antunes Rodrigues', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria Leonor Madeira da Costa Silva', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria Madalena Albuquerque Ferreira Freitas Simões', 11, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Martim Alves Beirão', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Martim Jorge Parreira Martins', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Miguel Ferreira Fernandes', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Nikole Zhou', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Óscar Zhou', 11, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Rodrigo Miguel Teixeira Gomes Coelho Lopo', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Tamar Zolondez', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Tiago Miguel Castro Ferreirinho', 11, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Tomás Macias Ribeiro dos Santos', 11, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Bartolomeu Miranda Saragga Igrejas', 10, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Catarina Alexandra Felício Nunes Tomás da Cruz', 10, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Domingos Soares Franco Sousa Franco', 10, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Duarte Maria Barreto da Gama Ochôa', 10, 'B1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Guilherme Duarte Carvalho Valente', 10, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Isabel Maria da Cunha Beltrão', 10, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Joana Sun Ye', 10, 'A1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria da Assunção Pereira Coutinho de Morais', 10, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Maria da Graça da Cruz Roseta Veloso', 10, 'C1', 'R25 - Curso de Técnico de Informática Sistemas'),
  ('Aleksandra Romanova da Cunha Teixeira', 12, 'B', 'Ciências e Tecnologias'),
  ('Benedita Van Uden Correia de Sá', 12, 'B', 'Ciências e Tecnologias'),
  ('Bernardo Monteiro Selidónio', 12, 'A', 'Ciências e Tecnologias'),
  ('Bernardo Soto Severino', 12, 'B', 'Ciências e Tecnologias'),
  ('Clara Dias Sequeira', 12, 'A', 'Ciências e Tecnologias'),
  ('Concha Gonzalez Rey de Sá Lima', 12, 'B', 'Ciências e Tecnologias'),
  ('Constança Maria Martins Calhorda Franco', 12, 'A', 'Ciências e Tecnologias'),
  ('David Simões Moreno', 12, 'B', 'Ciências e Tecnologias'),
  ('Diogo Godinho Ferreira', 12, 'A', 'Ciências e Tecnologias'),
  ('Francisco Maria Ribeiro Branco de Matos Pereira', 12, 'B', 'Ciências e Tecnologias'),
  ('Francisco Silva Pinto Vaz Pinto', 12, 'A', 'Ciências e Tecnologias'),
  ('Helena Maria dos Reis Jesus', 12, 'B', 'Ciências e Tecnologias'),
  ('Inês da Noiva Martins Monteiro Sapina', 12, 'B', 'Ciências e Tecnologias'),
  ('Inês Galvão de Melo de Lacerda e Mello', 12, 'A', 'Ciências e Tecnologias'),
  ('Inês Ganchas Soares', 12, 'A', 'Ciências e Tecnologias'),
  ('João Maria Gil Lima dos Santos', 12, 'B', 'Ciências e Tecnologias'),
  ('João Pedro Landeiro Capelo da Mota Caldeira', 12, 'A', 'Ciências e Tecnologias'),
  ('José Henrique Adriano Cruz', 12, 'B', 'Ciências e Tecnologias'),
  ('Laura Jorge Amaro', 12, 'A', 'Ciências e Tecnologias'),
  ('Leonor Maria Correia de Campos Lopes Cardoso', 12, 'A', 'Ciências e Tecnologias'),
  ('Leonor Taborda Ferreira Doriol Pena', 12, 'B', 'Ciências e Tecnologias'),
  ('Lorenzo Montero da Silva', 12, 'A', 'Ciências e Tecnologias'),
  ('Louisa Mary Correia de Campos Edwards', 12, 'A', 'Ciências e Tecnologias'),
  ('Madalena Bernardino Marques', 12, 'A', 'Ciências e Tecnologias'),
  ('Madalena da Cruz Martinho Macieira da Silva', 12, 'A', 'Ciências e Tecnologias'),
  ('Manuel Maria Sousa Rêgo Teixeira Botelho', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria Benedita de Quintanilha e Mendonça Lopes Cardoso', 12, 'A', 'Ciências e Tecnologias'),
  ('Maria do Carmo Correia de Campos Lopes Cardoso', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria do Rosário Pereira de Gouveia Correia de Campos', 12, 'A', 'Ciências e Tecnologias'),
  ('Maria Francisca Castelão dos Santos Quintas', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria Hermínia Pinheiro e Aragão', 12, 'A', 'Ciências e Tecnologias'),
  ('Maria Madalena Alves Coelho Enes de Oliveira', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria Rosa Saraiva Gonçalves dos Santos Frazão', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria Salgado Bordalo Rocha', 12, 'B', 'Ciências e Tecnologias'),
  ('Maria Teresa Stilwell Themudo Gilman', 12, 'B', 'Ciências e Tecnologias'),
  ('Mariana Ciríaco Ramos', 12, 'B', 'Ciências e Tecnologias'),
  ('Mariana Mineiro Fortuna Batista Nunes', 12, 'A', 'Ciências e Tecnologias'),
  ('Marta Carvalho dos Santos', 12, 'A', 'Ciências e Tecnologias'),
  ('Pedro Filgueira Rebouças de Oliveira', 12, 'B', 'Ciências e Tecnologias'),
  ('Rodrigo Ferreira Caldeira', 12, 'A', 'Ciências e Tecnologias'),
  ('Salvador Torre do Valle Monjardino', 12, 'A', 'Ciências e Tecnologias'),
  ('Sofia Aléxia da Rocha Marques', 12, 'A', 'Ciências e Tecnologias'),
  ('Sofia Roque de Pinho Naharro Pires', 12, 'A', 'Ciências e Tecnologias'),
  ('Teresa Maria Pereira Nilo', 12, 'A', 'Ciências e Tecnologias'),
  ('Tiago Moreira de Jesus Henriques Correia', 12, 'B', 'Ciências e Tecnologias'),
  ('Tiago Pedro Milagre', 12, 'B', 'Ciências e Tecnologias'),
  ('Vicente Magina Prazeres', 12, 'B', 'Ciências e Tecnologias'),
  ('Afonso de Santa Maria Bilbao Osório de Castro', 11, 'C', 'Ciências e Tecnologias'),
  ('Afonso Duarte Araújo Fontes Castanheira André', 11, 'C', 'Ciências e Tecnologias'),
  ('André Huang', 11, 'B', 'Ciências e Tecnologias'),
  ('António de Azevedo Soares Mineiro Rodrigues', 11, 'A', 'Ciências e Tecnologias'),
  ('António Maria Gonçalves Silva de Sousa', 11, 'B', 'Ciências e Tecnologias'),
  ('António Vasques Marinho Crespo Marques', 11, 'B', 'Ciências e Tecnologias'),
  ('Bernardo Elói Rito da Costa', 11, 'C', 'Ciências e Tecnologias'),
  ('Bithiah Josephine King Ting Wong', 11, 'A', 'Ciências e Tecnologias'),
  ('Carlota de Alpoim Moreira Madeira Marques', 11, 'C', 'Ciências e Tecnologias'),
  ('Carolina Ferreira Afonso', 11, 'B', 'Ciências e Tecnologias'),
  ('Daniela Radu Ignat', 11, 'C', 'Ciências e Tecnologias'),
  ('David Jacob Chagas', 11, 'B', 'Ciências e Tecnologias'),
  ('Dinis Bernardes de Luciano', 11, 'A', 'Ciências e Tecnologias'),
  ('Diogo Lourenço Raposo', 11, 'B', 'Ciências e Tecnologias'),
  ('Francisco Miguel Luís Martins', 11, 'A', 'Ciências e Tecnologias'),
  ('Francisco Xavier Coelho e Campos da Cruz Almeida', 11, 'A', 'Ciências e Tecnologias'),
  ('Francisco Xavier Rebelo de Andrade Saraiva de Ponte', 11, 'C', 'Ciências e Tecnologias'),
  ('Guilherme de Almeida Wan-Zeller Ryder', 11, 'C', 'Ciências e Tecnologias'),
  ('Guilherme Lorena Soller Coelho Nunes', 11, 'B', 'Ciências e Tecnologias'),
  ('Gustavo Marques Machado', 11, 'A', 'Ciências e Tecnologias'),
  ('Henrique Maria Bachofen Lehrfeld', 11, 'A', 'Ciências e Tecnologias'),
  ('Jaime Taveira de Castro Pinheiro Alves', 11, 'B', 'Ciências e Tecnologias'),
  ('João Filipe Cardoso Umbelina Dourado Laranjeira', 11, 'A', 'Ciências e Tecnologias'),
  ('João Marcelo Caetano Martin Lamy da Fontoura', 11, 'B', 'Ciências e Tecnologias'),
  ('João Maria Palma Alentejano Hassan', 11, 'A', 'Ciências e Tecnologias'),
  ('José Lopo de Vasconcelos Vaz de São Payo', 11, 'C', 'Ciências e Tecnologias'),
  ('Laura Sofia Faustino Moço', 11, 'A', 'Ciências e Tecnologias'),
  ('Leonor Maria Fernandes de Carvalho', 11, 'C', 'Ciências e Tecnologias'),
  ('Lourenço Correia de Campos de Melo Ramos', 11, 'B', 'Ciências e Tecnologias'),
  ('Maria Catarina Ribeiro da Rocha Melo da Silva', 11, 'B', 'Ciências e Tecnologias'),
  ('Maria Clara Araújo Frois Ferreira', 11, 'C', 'Ciências e Tecnologias'),
  ('Maria do Mar Lopes O connor Shirley', 11, 'B', 'Ciências e Tecnologias'),
  ('Maria do Mar Simplício Ramalho', 11, 'A', 'Ciências e Tecnologias'),
  ('Maria Francisca Ramalho Luís Fernandes', 11, 'C', 'Ciências e Tecnologias'),
  ('Maria Leonor Anjos Correia de Sá', 11, 'B', 'Ciências e Tecnologias'),
  ('Maria Luísa Rodrigues Ventura Bravo', 11, 'B', 'Ciências e Tecnologias'),
  ('Maria Moreira Rato de Castro', 11, 'C', 'Ciências e Tecnologias'),
  ('Maria Rocha Morais', 11, 'C', 'Ciências e Tecnologias'),
  ('Matias Carôco Pedro Maciel Cardoso', 11, 'A', 'Ciências e Tecnologias'),
  ('Miguel Franco Pereira Coutinho', 11, 'C', 'Ciências e Tecnologias'),
  ('Nuno Santiago de Bernardo Albuquerque e Carneiro Gomes', 11, 'A', 'Ciências e Tecnologias'),
  ('Paz Bobone Mendia de Castro', 11, 'B', 'Ciências e Tecnologias'),
  ('Pedro Maria Simões de Almeida Plantier', 11, 'B', 'Ciências e Tecnologias'),
  ('Pedro Martins Carrêto Lereno Monteiro', 11, 'C', 'Ciências e Tecnologias'),
  ('Tatiana Yang', 11, 'C', 'Ciências e Tecnologias'),
  ('Teresa Teixeira Lopes', 11, 'B', 'Ciências e Tecnologias'),
  ('Tiffany Ellen Cranston', 11, 'B', 'Ciências e Tecnologias'),
  ('Tomás João Quesado de Brito Santos Neves', 11, 'A', 'Ciências e Tecnologias'),
  ('Vicente Maria de Mendia de Castro de Lima Mayer', 11, 'A', 'Ciências e Tecnologias'),
  ('Yasmin Ye', 11, 'C', 'Ciências e Tecnologias'),
  ('André Maria Alves Coelho Enes de Oliveira', 10, 'C', 'Ciências e Tecnologias'),
  ('António Augusto Pereira de Gouveia Correia de Campos', 10, 'C', 'Ciências e Tecnologias'),
  ('Beatriz Cavaco Soares', 10, 'A', 'Ciências e Tecnologias'),
  ('Beatriz Lopes Barradas', 10, 'B', 'Ciências e Tecnologias'),
  ('Beatriz Saraiva Pousadas', 10, 'A', 'Ciências e Tecnologias'),
  ('Bosco Ye', 10, 'C', 'Ciências e Tecnologias'),
  ('Carlota Ferreira Marta Mora Neves', 10, 'B', 'Ciências e Tecnologias'),
  ('Carlota Maria Sousa Rêgo Teixeira Botelho', 10, 'B', 'Ciências e Tecnologias'),
  ('Carolina Sofia Teixeira de Almeida Gonçalves Figueiredo', 10, 'C', 'Ciências e Tecnologias'),
  ('Côme Pierre Joseph Schwerer', 10, 'A', 'Ciências e Tecnologias'),
  ('Diana Miranda de Oliveira', 10, 'A', 'Ciências e Tecnologias'),
  ('Duarte Fonseca Verde de Sousa', 10, 'C', 'Ciências e Tecnologias'),
  ('Duarte Picoto Madeira da Silva', 10, 'C', 'Ciências e Tecnologias'),
  ('Edward Harker Gonçalves Vicente', 10, 'B', 'Ciências e Tecnologias'),
  ('Francisca Moita Ramos Cosme Tomaz', 10, 'B', 'Ciências e Tecnologias'),
  ('Francisco Maria Correia de Campos Lopes Cardoso', 10, 'B', 'Ciências e Tecnologias'),
  ('Francisco Maria Noronha de Mello Bonneville', 10, 'C', 'Ciências e Tecnologias'),
  ('Francisco Paradela Silveira', 10, 'A', 'Ciências e Tecnologias'),
  ('Francisco Timóteo Ramos', 10, 'C', 'Ciências e Tecnologias'),
  ('Frederico Faria de Oliveira de Barros e Vasconcelos', 10, 'B', 'Ciências e Tecnologias'),
  ('Gonçalo dos Santos Gonçalves Martins', 10, 'C', 'Ciências e Tecnologias'),
  ('Gonçalo Nuno Patrício Salvado Alves', 10, 'B', 'Ciências e Tecnologias'),
  ('Gonçalo Simões Andrade', 10, 'B', 'Ciências e Tecnologias'),
  ('Guilherme Dias Arruda', 10, 'B', 'Ciências e Tecnologias'),
  ('Guilherme Leite Teixeira dos Santos Ferreira', 10, 'C', 'Ciências e Tecnologias'),
  ('Iurii Uvarov', 10, 'C', 'Ciências e Tecnologias'),
  ('Joana Reis Rodrigues', 10, 'B', 'Ciências e Tecnologias'),
  ('Joaquim Duarte Palma', 10, 'B', 'Ciências e Tecnologias'),
  ('José Diogo Buccellato Rodrigues de Oliveira', 10, 'A', 'Ciências e Tecnologias'),
  ('Josepha Abiah Chi Yin Wong', 10, 'A', 'Ciências e Tecnologias'),
  ('Julieta Mariño Martínez', 10, 'A', 'Ciências e Tecnologias'),
  ('Leonor Coutinho Azevedo', 10, 'B', 'Ciências e Tecnologias'),
  ('Lourenço Gonzalez Rey de Sá Lima', 10, 'C', 'Ciências e Tecnologias'),
  ('Lourenço Vasconcelos Maia', 10, 'C', 'Ciências e Tecnologias'),
  ('Lucas Pallister e Calaim', 10, 'A', 'Ciências e Tecnologias'),
  ('Luís Maria Roquette Durão Santos Silva', 10, 'C', 'Ciências e Tecnologias'),
  ('Luke Llewellyn Jenkinson', 10, 'B', 'Ciências e Tecnologias'),
  ('Madalena Braz Mendes Martins', 10, 'A', 'Ciências e Tecnologias'),
  ('Madalena Duarte Lucas Branco', 10, 'B', 'Ciências e Tecnologias'),
  ('Madalena Marques dos Reis Sequeira Costa', 10, 'A', 'Ciências e Tecnologias'),
  ('Mafalda de Magalhães Branco da Costa e Silva', 10, 'A', 'Ciências e Tecnologias'),
  ('Manuel Porfirio Rodrigues Canas Pereira', 10, 'A', 'Ciências e Tecnologias'),
  ('Maria Alves Luiz', 10, 'B', 'Ciências e Tecnologias'),
  ('Maria Francisca Pedroso Próspero dos Santos', 10, 'B', 'Ciências e Tecnologias'),
  ('Maria Inês Ferreira Bento', 10, 'A', 'Ciências e Tecnologias'),
  ('Maria Lousada de Jesus', 10, 'C', 'Ciências e Tecnologias'),
  ('Maria Luís Guerreiro Cruz Miranda de Melo', 10, 'B', 'Ciências e Tecnologias'),
  ('Maria Manuela Coelho dos Santos Tavares', 10, 'B', 'Ciências e Tecnologias'),
  ('Maria Teresa Pisani Burnay Tojal', 10, 'B', 'Ciências e Tecnologias'),
  ('Martim Ramos Correia Coelho e Campos', 10, 'C', 'Ciências e Tecnologias'),
  ('Natalia Elena Ember', 10, 'B', 'Ciências e Tecnologias'),
  ('Pedro da Cunha Martins da Câmara Pestana', 10, 'A', 'Ciências e Tecnologias'),
  ('Pedro Maria Cordeiro de Sousa Wemans', 10, 'C', 'Ciências e Tecnologias'),
  ('Pedro Maria Saraiva Gonçalves dos Santos Frazão', 10, 'C', 'Ciências e Tecnologias'),
  ('Rodrigo Terra Saraiva Borges Coelho', 10, 'A', 'Ciências e Tecnologias'),
  ('Salvador Maria de Sousa Duarte Aguiar Viegas', 10, 'B', 'Ciências e Tecnologias'),
  ('Sebastião Maria de Quintanilha e  Mendonça Lopes Cardoso', 10, 'A', 'Ciências e Tecnologias'),
  ('Simão Pedro Milagre', 10, 'C', 'Ciências e Tecnologias'),
  ('Sofia Chen', 10, 'A', 'Ciências e Tecnologias'),
  ('Sofia de Sousa Uva Vicente Simões', 10, 'A', 'Ciências e Tecnologias'),
  ('Suri Nahari Passos de Almeida', 10, 'A', 'Ciências e Tecnologias'),
  ('Thomas Huw Correia de Campos Edwards', 10, 'A', 'Ciências e Tecnologias'),
  ('Tomás Coelho e Campos da Cruz Almeida', 10, 'B', 'Ciências e Tecnologias'),
  ('Xavier Maria Aragonês Porfirio', 10, 'A', 'Ciências e Tecnologias')
) AS v(nome, ano, turma, ciclo_nome)
JOIN ciclos c ON c.nome = v.ciclo_nome
JOIN turmas t ON t.nome = v.turma AND t.ano = v.ano AND t.ciclo_id = c.id
WHERE NOT EXISTS (
  SELECT 1 FROM alunos a WHERE a.nome = v.nome AND a.turma_id = t.id
);

COMMIT;
